repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: check-shebang-scripts-are-executable
    -   id: check-executables-have-shebangs
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: debug-statements
    -   id: check-toml
    -   id: no-commit-to-branch
        args: ['--branch', 'main', '--branch', 'master']

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3.11

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings, flake8-bandit, flake8-bugbear]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]

-   repo: https://github.com/asottile/pytest-cov
    rev: v4.1.0
    hooks:
    -   id: pytest-cov
        additional_dependencies: [pytest-asyncio]

-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']

-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.1
    hooks:
    -   id: python-safety-dependencies-check

-   repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v14.4.0
    hooks:
    -   id: stylelint
        args: [--fix]
        additional_dependencies:
            - stylelint@14.4.0
            - stylelint-config-standard@24.0.0

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.42.0
    hooks:
    -   id: eslint
        files: \.(js|ts|jsx|tsx)$
        types: [file]
        additional_dependencies:
        -   eslint@8.42.0
        -   eslint-config-prettier@8.8.0
        -   '@typescript-eslint/eslint-plugin@5.59.9'
        -   '@typescript-eslint/parser@5.59.9'