version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    volumes:
      - ./restaurant.db:/app/restaurant.db
      - ./src:/app/src
    environment:
      - DATABASE_URL=sqlite:///./restaurant.db
      - PYTHONPATH=/app
      - PORT=10000
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - SENTRY_DSN=${SENTRY_DSN}
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 10000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:10000
      - PORT=3000
      - NODE_OPTIONS=--max-old-space-size=4096
    depends_on:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: 