"""Add quick order features and daily specials 2025-03-29

Revision ID: 7e18f9198f68
Revises: 071b9c08881a
Create Date: 2025-03-29 18:23:58.136418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e18f9198f68'
down_revision: Union[str, None] = '071b9c08881a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('meal_period', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('contains_daily_special', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    op.add_column('residents', sa.Column('preferred_table_id', sa.Integer(), nullable=True))
    op.add_column('residents', sa.Column('preferred_seat_number', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'residents', 'tables', ['preferred_table_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'residents', type_='foreignkey')
    op.drop_column('residents', 'preferred_seat_number')
    op.drop_column('residents', 'preferred_table_id')
    op.drop_column('orders', 'is_favorite')
    op.drop_column('orders', 'contains_daily_special')
    op.drop_column('orders', 'meal_period')
    # ### end Alembic commands ###
