name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Lint with Flake8
        run: |
          pip install flake8
          flake8 src/ tests/
      
      - name: Check formatting with Black
        run: |
          pip install black
          black --check src/ tests/
      
      - name: Type check with MyPy
        run: |
          pip install mypy
          mypy src/
      
      - name: Run Python tests
        run: |
          pip install pytest
          pytest tests/

  frontend-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: Install Node.js dependencies
        run: npm ci
      
      - name: Lint with ESLint
        run: |
          npx eslint "frontend/src/**/*.{ts,tsx}"
      
      - name: Check formatting with Prettier
        run: |
          npx prettier --check "frontend/src/**/*.{ts,tsx,js,jsx,css,html}"
      
      - name: Run frontend tests
        run: npm test
